name: Pull Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format Check
        run: make fmt-check
      - name: Test
        run: make test
