name: Release

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Format Check
        run: make fmt-check
      - name: Test
        run: make test
      - name: Build
        run: make build
